spring:
  application:
    name: kafka
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


  kafka:
    bootstrap-servers: localhost:9092
    producer:
      transaction-id-prefix: tx-producer-
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        enable.idempotence: true
        acks: all
    consumer:
      group-id: bank-consumer-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  outbox:
    poll-interval-ms: ${OUTBOX_POLL_INTERVAL_MS}
    batch-size: ${OUTBOX_BATCH_SIZE}
  topic:
    name: bank-ops

logging:
  level:
    root: INFO